---
title: "Incomplete association simulation with Splatter"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())

library(splatter)
library(Seurat)

sparsity_level = .95

sim <- splatSimulate(group.prob=c(0.6, 0.4), nGenes=5000, batchCells=c(300, 750),
                     dropout.type='experiment', method= 'groups' ,seed=17, dropout.shape=-1, 
                     dropout.mid=3.9, 
                     de.prob = c(0.05, 0.05),
                     de.downProb = c(0.4, 0.4),
                     de.facLoc = 0.05,
                     de.facScale = 0.05,
                     batch.facLoc=0.01,
                     batch.facScale=0.01
                    )


tmpcount = counts(sim)
colsum = colSums(tmpcount == 0)
simsparsity = sum(colsum)/(5000*(300 + 750))
print("raw sparsity")
print(simsparsity)
```

```{r}
counts <- as.data.frame(counts(sim))
geneinfo <- as.data.frame(rowData(sim))
cellinfo <- as.data.frame(colData(sim))

rowsum = rowSums(tmpcount==0)/length(colnames(tmpcount))
non_sparse_genes = rownames(tmpcount)[which(rowsum < sparsity_level)]
counts <- tmpcount[non_sparse_genes, ]
geneinfo <- geneinfo[non_sparse_genes, ]

rowsum = rowSums(counts == 0)
simsparsity = sum(rowsum)/(length(rownames(counts)) * length(colnames(counts)) )
print("after filtered sparsity")
print(simsparsity)
```

```{r}
de_genes_ls <- rownames(geneinfo[(geneinfo$DEFacGroup1+geneinfo$DEFacGroup2)!=2,])
de_genes_df <- geneinfo[de_genes_ls,]

down_genes <- rownames(de_genes_df[de_genes_df$DEFacGroup1<de_genes_df$DEFacGroup2,])
up_genes <- de_genes_ls[!de_genes_ls %in% down_genes]
genes_deg <- c(up_genes, down_genes)

# Normal simulation distribution 
seu <- CreateSeuratObject(counts = counts)
seu <- AddMetaData(seu, cellinfo$Batch, col.name = "Batch")
seu <- AddMetaData(seu, cellinfo$Group, col.name = "Group")
seu <- SCTransform(seu)

# PCA
seu <- RunPCA(seu, npcs = 30, verbose = FALSE)
# TSNE
seu <- RunUMAP(seu, dims = 1:30, seed.use = 7968)

DimPlot(seu, reduction = "umap",
        group.by = "Group", shape.by="Batch", pt.size = 2,label = F, repel = T)
```

``` {r}
#Incomplete association manipulation
a = b = 2

batch1 = batch1_ori = counts[, which(cellinfo$Batch=='Batch1')]
batch2 = batch2_ori = counts[, which(cellinfo$Batch=='Batch2')]

N = round(length(de_genes_ls)/3)
non_DEG = geneinfo$Gene[!geneinfo$Gene %in% de_genes_ls]

############################# batch 1
separated_DEG_1 = sample(non_DEG, N, replace=FALSE)
tumor = which(cellinfo$Group[which(cellinfo$Batch=='Batch1')]=='Group2')

tmp <- batch1[separated_DEG_1, tumor]
for (g in rownames(tmp)){
  for (c in colnames(tmp)){
    prob = rbeta(1, a, b)
    tmp[g, c] = rbinom(1, tmp[g, c], prob=prob) %/% 2
  }
}
tmp <- round(tmp)
tmp -> batch1[separated_DEG_1, tumor]

############################# batch 2
separated_DEG_2 = sample(non_DEG, N/2, replace=FALSE)
some_1 <- sample(separated_DEG_1, N/2, replace=FALSE)
separated_DEG_2 = c(separated_DEG_2, some_1)
  
tumor = which(cellinfo$Group[which(cellinfo$Batch=='Batch2')]=='Group2')

tmp <- batch2[separated_DEG_2, tumor]
for (g in rownames(tmp)){
  for (c in colnames(tmp)){
    prob = rbeta(1, a, b)
    tmp[g, c] = rbinom(1, tmp[g, c], prob=prob) %/% 2
  }
}
tmp <- round(tmp)
tmp -> batch2[separated_DEG_2, tumor]


batch1 -> counts[, which(cellinfo$Batch=='Batch1')]
batch2 -> counts[, which(cellinfo$Batch=='Batch2')]

seu <- CreateSeuratObject(counts = counts)
seu <- AddMetaData(seu, cellinfo$Batch, col.name = "Batch")
seu <- AddMetaData(seu, cellinfo$Group, col.name = "Group")
seu <- SCTransform(seu)

# PCA
seu <- RunPCA(seu, npcs = 30, verbose = FALSE)
# UMAP
seu <- RunUMAP(seu, dims = 1:30, seed.use = 7968)

DimPlot(seu, reduction = "umap",
        group.by = "Group", shape.by="Batch", pt.size = 2,label = F, repel = TRUE)

```